repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=80]

  # - repo: https://github.com/pycqa/flake8
  #   rev: 4.0.1
  #   hooks:
  #     - id: flake8
  #       args: [
  #         --max-line-length=88,
  #         --extend-ignore=E203,W503,E501,F401,F541,D100,D101,D102,D103,D104,D105,D106,D107,D200,D202,D400,D401
  #       ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.950
    hooks:
      - id: mypy
        additional_dependencies: [pygame]
        args: [--ignore-missing-imports]

  - repo: local
    hooks:
      - id: tests
        name: Run tests
        entry: bash
        language: system
        pass_filenames: false
        always_run: true
        args: [-c, "cd snake && pytest tests/ -q"]

      - id: check-version
        name: Check version consistency
        entry: bash
        language: system
        pass_filenames: false
        always_run: true
        args:
          - -c
          - |
            cd snake
            python -c "
            import snake_game
            import re
            with open('pyproject.toml') as f:
                pyproject_content = f.read()
            version_match = re.search(r'version\s*=\s*[\"\'](.*?)[\"\']', pyproject_content)
            if not version_match:
                raise ValueError('Could not find version in pyproject.toml')
            pyproject_version = version_match.group(1)
            if snake_game.__version__ != pyproject_version:
                raise ValueError(f'Version mismatch: snake_game.__version__={snake_game.__version__} != pyproject.toml version={pyproject_version}')
            print(f'✅ Version {snake_game.__version__} is consistent between snake_game/__init__.py and pyproject.toml')
            "

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
